---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: allow-linkerd-identity-to-cr
  namespace: linkerd
rules:
  - apiGroups:
      - "cert-manager.io"
    resources:
      - "certificaterequests"
    verbs:
      - "get"
      - "list"
      - "create"
      - "update"
      - "delete"
      - "watch"
  - apiGroups:
      - "coordination.k8s.io"
    resources:
      - "leases"
    verbs:
      - "get"
      - "create"
      - "update"
      - "watch"
      - "list"
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["create"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: linkerd-identity
  namespace: linkerd
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: allow-linkerd-identity-to-cr
subjects:
  - kind: ServiceAccount
    name: linkerd-identity
    namespace: linkerd
---
